### ISSUE TITLE
website down, robotwebtools.org

### ISSUE THREAD

**Issue by Tjaart-Hobby** [RobotWebTools/ros3djs#613] opened 2023-04-10 00:07 UTC
**Description**
The code depency? website 'robotwebtools.org' has been down for more than a week.

- Library Version:
- ROS Version:Noetic
- Platform / OS: Ubuntu 20.04

**Steps To Reproduce**

click on "demo" of code in read-me

**Expected Behavior**
open website

**Actual Behavior**

**Comment by MatthijsBurgh** [comment] 2023-04-10 05:00
Duplicate of https://github.com/RobotWebTools/robotwebtools.github.io/issues/82

**Closed as completed by MatthijsBurgh** 2023-04-10 05:00 UTC
Labels: bug
